import { PrismaTransactionClient } from '../prisma.client';
import {
  ProjectRepository,
  ProjectRecord,
  CreateProjectDto,
  UpdateProjectDto,
} from '../../../core/repositories';
import { ProjectStatus } from '@hackathon/contracts';

export class PrismaProjectRepository implements ProjectRepository {
  constructor(private readonly prisma: PrismaTransactionClient) {}

  async findById(id: string): Promise<ProjectRecord | null> {
    const project = await this.prisma.project.findUnique({
      where: { id }
    });
    if (!project) return null;
    return this.mapToDomain(project);
  }

  async findByTeamId(teamId: string): Promise<ProjectRecord | null> {
    const project = await this.prisma.project.findFirst({
      where: { teamId }
    });
    if (!project) return null;
    return this.mapToDomain(project);
  }

  async findAll(): Promise<ProjectRecord[]> {
    const projects = await this.prisma.project.findMany();
    return projects.map((p: any) => this.mapToDomain(p));
  }

  async create(data: CreateProjectDto): Promise<ProjectRecord> {
    const project = await this.prisma.project.create({
      data: {
        id: data.id!, // Assuming id is generated by domain and provided
        title: data.title,
        summary: data.description,
        repoUrl: data.repositoryUrl || '',
        demoUrl: data.demoUrl !== undefined ? data.demoUrl : null,
        status: data.status || 'submitted',
        teamId: data.teamId,
        trackId: data.trackId,
        submittedAt: data.submittedAt || new Date(),
      }
    });
    return this.mapToDomain(project);
  }

  async update(id: string, data: UpdateProjectDto): Promise<ProjectRecord> {
    const updateData: any = {};
    if (data.trackId !== undefined) updateData.trackId = data.trackId;
    if (data.title !== undefined) updateData.title = data.title;
    if (data.description !== undefined) updateData.summary = data.description;
    if (data.repositoryUrl !== undefined) updateData.repoUrl = data.repositoryUrl;
    if (data.demoUrl !== undefined) updateData.demoUrl = data.demoUrl;
    if (data.status !== undefined) updateData.status = data.status;
    if (data.submittedAt !== undefined) updateData.submittedAt = data.submittedAt;

    const project = await this.prisma.project.update({
      where: { id },
      data: updateData
    });
    return this.mapToDomain(project);
  }

  private mapToDomain(project: any): ProjectRecord {
    return {
      id: project.id,
      teamId: project.teamId,
      trackId: project.trackId,
      title: project.title,
      description: project.summary,
      repositoryUrl: project.repoUrl,
      demoUrl: project.demoUrl,
      status: project.status as ProjectStatus,
      submittedAt: project.submittedAt,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    };
  }
}
