import { z } from 'zod';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_SESSION: 'INVALID_SESSION',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ALREADY_HAS_PROJECT: 'ALREADY_HAS_PROJECT',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  SUBMISSION_DEADLINE_PASSED: 'SUBMISSION_DEADLINE_PASSED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_VOTING_MODE: 'INVALID_VOTING_MODE',
  VOTING_NOT_OPEN: 'VOTING_NOT_OPEN',
  VOTING_CLOSED: 'VOTING_CLOSED',
  DUPLICATE_VOTE: 'DUPLICATE_VOTE',
  VOTE_LIMIT_EXCEEDED: 'VOTE_LIMIT_EXCEEDED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_USED: 'OTP_USED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const errorCodeSchema = z.enum([
  ERROR_CODES.UNAUTHORIZED,
  ERROR_CODES.INVALID_SESSION,
  ERROR_CODES.FORBIDDEN,
  ERROR_CODES.VALIDATION_ERROR,
  ERROR_CODES.NOT_FOUND,
  ERROR_CODES.CONFLICT,
  ERROR_CODES.ALREADY_HAS_PROJECT,
  ERROR_CODES.ALREADY_SUBMITTED,
  ERROR_CODES.SUBMISSION_DEADLINE_PASSED,
  ERROR_CODES.INTERNAL_SERVER_ERROR,
  ERROR_CODES.INVALID_VOTING_MODE,
  ERROR_CODES.VOTING_NOT_OPEN,
  ERROR_CODES.VOTING_CLOSED,
  ERROR_CODES.DUPLICATE_VOTE,
  ERROR_CODES.VOTE_LIMIT_EXCEEDED,
  ERROR_CODES.INVALID_OTP,
  ERROR_CODES.OTP_EXPIRED,
  ERROR_CODES.OTP_USED,
  ERROR_CODES.RATE_LIMIT_EXCEEDED,
]);

export const apiErrorPayloadSchema = z.object({
  code: errorCodeSchema,
  message: z.string(),
  details: z.unknown().optional(),
});

export type ApiErrorPayload = z.infer<typeof apiErrorPayloadSchema>;

export const apiErrorResponseSchema = z.object({
  error: apiErrorPayloadSchema,
});

export type ApiErrorResponse = z.infer<typeof apiErrorResponseSchema>;

export const apiSuccessResponseSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.object({
    data: dataSchema,
  });
